name: Build and Deploy Vite App to Needle Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build:production
        env:
          NEEDLE_CLOUD_TOKEN: ${{ secrets.NEEDLE_CLOUD_TOKEN }}

      - name: Deploy to Needle Cloud
        id: deploy
        run: |
          # Run the deployment command and capture output
          DEPLOY_OUTPUT=$(npx needle-cloud deploy ./dist --name vite-template --token ${{ secrets.NEEDLE_CLOUD_TOKEN }})
          
          # Extract the URL from the output (adjust the grep pattern as needed)
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^ ]*' | head -1)
          
          # Set the URL as an output variable
          echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          
          # Add URL to the job summary
          echo "## 🚀 Deployment Complete!" >> $GITHUB_STEP_SUMMARY
          echo "Deployed to: [$DEPLOY_URL]($DEPLOY_URL)" >> $GITHUB_STEP_SUMMARY
        env:
          NODE_ENV: production
          NEEDLE_CLOUD_TOKEN: ${{ secrets.NEEDLE_CLOUD_TOKEN }}
          
      - name: Display deployment URL
        run: |
          echo "::notice title=Deployment URL::Deployed to ${{ steps.deploy.outputs.deploy_url }}"